### ISSUE TITLE
Waiting for contributors.

### ISSUE THREAD

**Issue by InfoDevkota** [InfoDevkota/phpformmysql#1]

**Comment by bhaskarmac** [comment]
@InfoDevkota What exactly needs to be implemented in this repo?

**Comment by higagan-zz** [comment]
Interested!

**Comment by MohitDeshwal** [comment]
Interested Too!

**Comment by PrajapatiAnkit** [comment]
what is to be done in this repo??
i want to work on it. may I know??

**Comment by InfoDevkota** [comment]
As the description of the repo: 
`A simple php form to add data in database.. Without any validation.`
We need a better and easy to understand code.
Thanks everyone for the interest. :)
